- name: Install jq
  apt:
    update_cache: yes
    name:
      - jq
    state: latest

- name: Install yq
  get_url:
    url: "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
    dest: "/usr/local/bin/yq"
    mode: "0755"

